### ISSUE TITLE
HotChocolate v13.7.0+ support

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation-hotchocolate#51]
Due to a breaking change to the public API, we cannot support newer versions of `HotChocolate` until their replacement API (currently work in progress) is complete.

**Comment by cli00004** [comment]
Right, noticed we are getting this exception after upgrading to Hotchocolate 13.7, hopefully a fix will come out soon, thanks

  System.TypeLoadException: Method 'OnBeforeCreateSchema' on type 'ApolloGraphQL.HotChocolate.Federation.FederationTypeInterceptor' from assembly 'ApolloGraphQL.HotChocolate.Federation, Version=1.3.0.0, Culture=neutral, Publi
cKeyToken=null' is overriding a method that is not visible from that assembly.
         at HotChocolate.ApolloFederationSchemaBuilderExtensionsV2.AddApolloFederationV2Definitions(ISchemaBuilder builder, FederationVersion version)
         at HotChocolate.ApolloFederationSchemaBuilderExtensionsV2.AddApolloFederationV2(ISchemaBuilder builder, FederatedSchema schema)
         at Microsoft.Extensions.DependencyInjection.ApolloFederationRequestExecutorBuilderExtensionsV2.<>c__DisplayClass1_0.<AddApolloFederationV2>b__0(ISchemaBuilder s)
         at Microsoft.Extensions.DependencyInjection.RequestExecutorBuilderExtensions.<>c__DisplayClass0_0.<ConfigureSchema>b__1(ConfigurationContext ctx, IServiceProvider _)
         at HotChocolate.Execution.RequestExecutorResolver.OnConfigureSchemaBuilderAsync(ConfigurationContext context, IServiceProvider schemaServices, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonit
or typeModuleChangeMonitor, CancellationToken cancellationToken)
